### ISSUE TITLE
Wrong Python dependencies information in 0.16.2_5 package

### ISSUE THREAD

**Issue by traversaro** [conda-forge/libode-feedstock#9]
* `libode` package should not depend on Python, but instead in its index.json it seems to contain:
~~~
{
  "arch": "x86_64",
  "build": "h9c3ff4c_5",
  "build_number": 5,
  "depends": [
    "libgcc-ng >=9.3.0",
    "libstdcxx-ng >=9.3.0",
    "pthread-stubs",
    "python_abi 3.8.* *_cp38"
  ],
  "license": "LGPL-2.1-or-later OR BSD-4-Clause",
  "name": "libode",
  "platform": "linux",
  "subdir": "linux-64",
  "timestamp": 1616591801454,
  "version": "0.16.2"
}
~~~
* ~pyode (the pytbon bindings of ode) should be available not only for Python 3.8, but also for the other supported versions.~ Fixed by https://github.com/conda-forge/libode-feedstock/pull/10

**Comment by traversaro** [comment]
> `libode` package should not depend on Python, but instead in its index.json it seems to contain:

Not sure about the root source of this, probably some run_exports somewhere. I guess we could adopt the workaround in https://github.com/conda/conda-build/issues/3956#issuecomment-845711269 .

**Comment by traversaro** [comment]
The second point is fixed by https://github.com/conda-forge/libode-feedstock/pull/10, and it makes the first point less urgent.

**Comment by traversaro** [comment]
The first point is probably due to the `run_exports` of the python package on the `python_abi` package, see https://github.com/conda-forge/blog/blob/61776af89facd44997ac512e26e433506cccf8e3/posts/2020-03-10-pypy.rst#python_abi-package and https://github.com/conda-forge/python-feedstock/blob/835aeb3e9a0e8a28d86d50bfdbb9463c02bbc80e/recipe/meta.yaml#L164 . We can probably solve it by adding a ignore_run_exports command under outputs, I was not sure if this was possible from docs, but it seems to be done: https://github.com/conda-forge/python-feedstock/blob/835aeb3e9a0e8a28d86d50bfdbb9463c02bbc80e/recipe/meta.yaml#L134 .

**Comment by wolfv** [comment]
yes, builds with multiple outputs have a couple of "surprises" unfortunately. 

Should we move the previous packages to broken? I think you're right, you coudl add a `ignore_run_exports`. I am not sure if repeating `build` and `host` would also overwrite the `run_exports` from the toplevel-build.

**Comment by traversaro** [comment]
> Should we move the previous packages to broken?

Good point, however for the problem in https://github.com/conda-forge/gazebo-feedstock/issues/79 the issue seems more that `gazebo-11.5.1-haa37ec6_2` does not have the correct constraint w.r.t. to libode, as according to run_exports it should require libode >= 0.16.2, but libode 0.16 is instead installed, so the problem seems more on the Gazebo side rather then libode.
